import = ["/home/filipe/.config/alacritty/settings.toml"]

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#32302f"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
# soft contrast: background = "#32302f"
# normal contrast: background = "#282828"
# hard contrast: background = "#1d2021"
background = "#1d2021"
foreground = "#ebdbb2"
