[general]
import = ["/home/filipe/.config/alacritty/settings.toml"]

[colors.bright]
black = "#928374"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"

[colors.normal]
black = "#f2e5bc"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#7c6f64"

[colors.primary]
# soft contrast: background = "#f2e5bc"
# normal contrast: background = "#fbf1c7"
# hard contrast: background = "#f9f5d7"
background = "#f9f5d7"
foreground = "#3c3836"
