[cursor]
thickness = 0.0
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
COLORTERM = "truecolor"
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
