# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: alacritty
  COLORTERM: truecolor
  WINIT_X11_SCALE_FACTOR: "1"

window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 0
    y: 0

scrolling:
  history: 100000

font:
  normal:
    family: Iosevka Term
    style: Regular
  bold:
    family: Iosevka Term
    style: Bold
  italic:
    family: Iosevka Term
    style: Italic
  bold_italic:
    family: Iosevka Term
    style: Bold Italic
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  unfocused_hollow: true
  thickness: 0.0
  style:
    blinking: Off
    shape: Block

key_bindings:
  - { key: F11, action: ToggleFullscreen }
