#!/bin/bash

while getopts "f" opt; do
	case "$opt" in
		"f")
			export DOTFILES_FULL=1
			;;
		*)
			echo "Unsupported option. Exiting."
			exit 1
			;;
	esac
done

echo "#########################"
echo "# Beggining instalation #"
echo "#########################"

sudo echo "# Getting password..."

echo "# Pacman"
./packages.sh

echo "# AUR"
./aur.sh

echo "# Linker"
if [[ "$(basename $PWD)" != "dotfiles" ]]; then
	cd ..
fi
sed -n "/Headless/,/Desktop/p" "README.md" | head --lines -2 | tail --lines +3 | cut -d' ' -f2 | xargs -I {} stow --restow {}
if [[ -n "$DOTFILES_FULL" ]]; then
	sed -n "/Desktop/,/#/p" "README.md" | head --lines -2 | tail --lines +3 | cut -d' ' -f2 | xargs -I {} stow --restow {}
fi

echo "# Post instalation things..."
./post.sh

unset DOTFILES_FULL
