[username]
disabled = false
show_always = true

[hostname]
ssh_only = false
disabled = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"

#[time]
#style = "bold white"
#disabled = false

#[cmd_duration]
#show_milliseconds = true
#style = "bold green"
